#!/bin/bash

#echo $@
#echo $PWD
#echo $CWD
#echo $(dirname "$0")
export __file__=$(dirname "$0")
if [ -z $__file__ ] || [ -z $1 ] || [ -z $2 ]; then
    echo "Error: No __file__ specified"
    exit 1
fi
echo $__file__
#$PWD/pack-pbp $@
cp -f $PWD/$1 $__file__/data.psp
$__file__/pack-pbp $PWD/$2 \
	$__file__/param.sfo \
	$__file__/icon0.png \
	$__file__/icon1.pmf \
	$__file__/pic0.png \
	$__file__/pic1.png \
	$__file__/snd0.at3 \
	$__file__/data.psp \
	$__file__/data.psar

exit 0
